[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/run"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"

[[headers]]
  for = "/run.ps1"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"
